// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://camfzwxmvnswqvqxnutv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbWZ6d3htdm5zd3F2cXhudXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjAxMTQsImV4cCI6MjA2MDM5NjExNH0.BGaFkEMBhUUfjXowNzMvqL2EX7pYw7HQh5rFyVPk-uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);